### ISSUE TITLE
[Python] I'm not sure if it's a bug

### ISSUE THREAD

**Issue by GH1995** [honza/vim-snippets#1133] opened 2019-07-11 07:36 UTC
# Suddenly, `self` ! 

My vim config is 
```vimrc
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.                                        
let g:UltiSnipsExpandTrigger="<c-b>"                                                                                                   
let g:UltiSnipsJumpForwardTrigger="<c-b>"
```

![c-b](https://user-images.githubusercontent.com/11362493/61031081-61840a80-a3f1-11e9-8bb0-ba33dd064710.gif)

**Comment by sim590** [comment] 2019-09-23 19:22
Yes. I'm having the exact same issue. That's annoying. It has been here for a long time. I don't know the cause...

**Comment by sim590** [comment] 2019-09-23 19:24
@GH1995 Change the title to something meaningful. It is hard to find this bug in the list when the issue title is not saying what it is about. May be:

> [python] def suddenly appears in args of function (snip: deff)

**Comment by SirVer** [comment] 2019-11-09 07:18
Closing as duplictae of #961

**Closed by SirVer** 2019-11-09 07:18 UTC
