### ISSUE TITLE
javascript.es6.react.snippets not working..

### ISSUE THREAD

**Issue by fdelacruz** [honza/vim-snippets#952] opened 2017-07-13 18:54 UTC
I tried doing as per the documentation:

- :UltiSnipsAddFiletype javascript.es6.react

- used .vim/ftplugin/javascript.vim

- autocmd FileType javascript UltiSnipsAddFiletypes javascript.es6.react

..to no avail.

On the other, hand javascript-mocha which is in the same path is working fine which means it is NOT the snippet engine.

**Comment by fdelacruz** [comment] 2017-07-22 05:00
Any idea what so ever, as to what I'm doing wrong??

**Comment by fdelacruz** [comment] 2017-07-23 17:29
So not one of the four contributors of the thing @michaelghinrichs, @mauroporrasp, @bannier, @codeinabox has a word to say about this issue.

**Comment by codeinabox** [comment] 2017-07-23 20:34
To confirm are you using Ultisnips or a different snippet engine?

**Comment by fdelacruz** [comment] 2017-07-23 20:51
Hi @codeinabox, I'm using Ultisnips.

**Comment by codeinabox** [comment] 2017-07-24 09:55
@fdelacruz first off sorry you haven't received an answer. This project is run by volunteers, if you want answer from a contributor it's good to start with please rather than just mentioning them.

I've had a look into this and I am wondering if the issue is it uses dots instead of dashes. @lpil I was under the impression that dashes are used for vendor snippets and dots for multi-syntax snippets? I could make a PR to change it if that's the problem.

**Comment by lpil** [comment] 2017-07-24 10:21
Hi @fdelacruz, please be civil and polite when asking people to donate their time to help you for free.

I feel does should work but I know little about the details of this ultisnips feature. I'm on a train now so can't investigate right now I'm afraid

**Comment by bannier** [comment] 2017-07-24 11:38
@fdelacruz doesn't work anymore for me too, nor mocha snippets. looks like javascript related snippets won't load outside of `javascript` directory

**Comment by bannier** [comment] 2017-07-24 12:05
moving `javascript.es6.react.snippets` file to `javascript` directory solves the issue for me

**Comment by lpil** [comment] 2017-07-24 13:57
If we put it there it is loaded by default, which may not be the behaviour we want. Do we want to make ES6 the default? If so we should probably move some or all the snippets into the regular javascript file.

**Comment by fdelacruz** [comment] 2017-07-24 14:58
Apologies for the rudeness earlier.
That said, thanks for taking a look a this.
As for javascript-mocha.snippets, mine are working fine.

**Comment by fdelacruz** [comment] 2017-07-24 15:03
@codeinabox using dashes instead of dots seems to fix the problem.

**Comment by code-hunger** [comment] 2017-12-27 11:54
I can confirm that linking *javascript.es6.react.snippets* to *javascript-es6-react.snippets* solves the problem for me, too, so I think this change deserves to go to the repo.
Unless I'd looked here for the issues, I wouldn't have had working React snippets!

**Comment by lpil** [comment] 2017-12-27 12:56
That would result in them being loaded by default. Our policy is that library snippets are not to be opt-in, not the default. Going to close this to avoid confusion.

Perhaps we could do with a documentation update for this.

**Closed by lpil** 2017-12-27 12:56 UTC

**Comment by code-hunger** [comment] 2017-12-27 13:04
No, it doesn't, at least for me. I started vim with a javascript.jsx file and the snippets were not imported.
I had to manually enter `:UltiSnipsAddFiletype javascript-es6-react` to import them.

**Comment by lpil** [comment] 2017-12-27 13:31
Oh yes, terribly sorry, I got confused! The name with the dots is incorrect, it should use dashes.

Thanks for catching my mistake there @code-hunger. I'll update the name

**Comment by Tallestthomas** [comment] 2018-07-04 04:47
This issue is marked as closed by I ran into the same issue.
Moving the `javascript-es6-react.snippets` file into the `javascript/` directory seems to be the fix though. 

Can open a PR if needed

**Comment by lpil** [comment] 2018-07-04 14:08
Moving it into the javascript directory means those snippets are loaded by default for the Javascript filetype, which is not the desired behaviour. Library snippets are to be opt-in.

**Comment by benlieb** [comment] 2020-05-14 20:07
> @codeinabox using dashes instead of dots seems to fix the problem.
> So javascript-es6-react.snippets instead of javascript.es6.react.snippets

This is the only thing that worked for me

**Comment by lpil** [comment] 2020-05-14 20:10
@benlieb please see the readme for instructions on how to enable non default snippets
