### ISSUE TITLE
Allow users to specify whether they want double or single quotes

### ISSUE THREAD

**Issue by lpil** [honza/vim-snippets#682] opened 2016-02-12 10:02 UTC
The Ruby and Javascript languages seem like they would benefit from this.

The user could set a flag to indicate which to use.

```viml
let g:snips_ruby_quote="single"
let g:snips_javascript_quote="double"
```

**Comment by shepherdsam** [comment] 2016-03-10 14:48
I'd use this for sure.

**Comment by juanibiapina** [comment] 2016-03-25 14:05
Duplicate of #677 , so I've added my two cents there.

**Closed** 2016-04-05 18:09 UTC
